name: DHCP server
description: A simple DHCP server
version: 1.0.0
slug: dhcp_server
init: false
startup: system
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

host_network: true
advanced: true

options:
  default_lease: 86400
  dns:
    - 8.8.8.8
    - 8.8.4.4
  ntp: []
  domain: null
  hosts: []
  max_lease: 172800
  networks:
    - broadcast: 192.168.1.255
      gateway: 192.168.1.1
      interface: eth0
      netmask: 255.255.255.0
      range_end: 192.168.1.200
      range_start: 192.168.1.100
      subnet: 192.168.1.0
      next-server: 192.168.0.37
      filename: grubnetx64.efi
schema:
  default_lease: int
  dns:
    - str
  ntp:
    - str
  domain: str
  hosts:
    - ip: str
      mac: str
      name: str
  max_lease: int
  networks:
    - broadcast: str
      gateway: str
      interface: str
      netmask: str
      range_end: str
      range_start: str
      subnet: str
      next-server: str
      filename: str
